### ISSUE TITLE
Checking `Application.HasProLicense();` doesn't work on newer versions of Unity that have the dark theme enabled

### ISSUE THREAD

**Issue by MostHated** [noisecrime/Unity-AssetStoreOrganizer#1]
Hey there,
    I just wanted to let you know that it looks like using `Application.HasProLicense();` to determine the theme color doesn't quite give the desired results in newer versions of Unity that have the dark theme enabled.

<details>
<summary>When using the "HasProLicense() check</summary>

![](https://i.imgur.com/yDRRTSB.png)

</details>

Here I just did `bool hasProLicense  = !Application.HasProLicense();`

<details>
<summary>Inverting the license check</summary>

![](https://i.imgur.com/Z5SmlK2.png)

</details>

I also wanted to request that having the 'latest update' as a column/category would be super helpful in deciding what to archive. If a tool has not received an update in 3 years, it definitely helps to be able to see that at a glance.

Just wanted to let you know what I came across. :+1: 
Thanks,
-MH

**Comment by noisecrime** [comment]
Thanks for that - out of interest what version of Unity are you seeing this in? I'm generally stuck on 2019.4 at present for projects and guess I haven't tested on later versions in a while.

Not sure I entirelly follow the 'latest update' suggestion. We already have both downloaded and published dates columns. Unfortunately at present the project is unable to retrieve any actual information about the package beyond what is in the downloaded packages - it can't check for an updated package for example. 

Its something I hope to look into a gain at some point, but its completely dependent upon whether Unity exposes that information via the new package api or not. Honestly i'm not too hopeful as I tried to do this via the web store api years ago and that information seemed to be hidden behind a valid login token.

As for archiving, the intended use is simply to archive everything that has not previously be archived. As the project maintains multiple version copies of each package you wont lose access to older versions in the archive.

Anyway thanks again for trying it out and reporting the bug.
